//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransaccionesAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Easy_Pay
    {
        public int EPID { get; set; }
        public int USRID { get; set; }
        public string Usuario { get; set; }
        public string Nombre { get; set; }
        public string Correo { get; set; }
        public string Num_Cuenta { get; set; }
        public string Cod_Seguridad { get; set; }
        public string Password { get; set; }
        public double Fondos { get; set; }
    }
}
