//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransaccionesAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta
    {
        public int TID { get; set; }
        public int USRID { get; set; }
        public int Num_Tarjeta { get; set; }
        public int Exp_Month { get; set; }
        public int Exp_Year { get; set; }
        public int CVV { get; set; }
        public string Tipo_Tarjeta { get; set; }
        public string Tipo { get; set; }
        public Nullable<double> Limite_Tarjeta { get; set; }
        public double Fondos { get; set; }
    }
}
